import { type NextRequest, NextResponse } from "next/server"

// Auto-learning system for bot detection patterns
interface LearningPattern {
  id: string
  pattern: string
  category: string
  confidence: number
  detectionCount: number
  lastSeen: string
  autoGenerated: boolean
  accuracy: number
}

interface LearningStats {
  totalPatterns: number
  autoGeneratedPatterns: number
  averageAccuracy: number
  topCategories: Array<{
    category: string
    count: number
  }>
  recentLearning: Array<{
    timestamp: string
    pattern: string
    confidence: number
  }>
}

const learningPatterns: LearningPattern[] = [
  {
    id: "1",
    pattern: "googlebot",
    category: "search_engine",
    confidence: 0.95,
    detectionCount: 45,
    lastSeen: new Date().toISOString(),
    autoGenerated: false,
    accuracy: 0.98,
  },
  {
    id: "2",
    pattern: "integral.*ad.*science",
    category: "ad_verification",
    confidence: 0.99,
    detectionCount: 23,
    lastSeen: new Date().toISOString(),
    autoGenerated: true,
    accuracy: 0.97,
  },
  {
    id: "3",
    pattern: "headless.*chrome",
    category: "automation",
    confidence: 0.85,
    detectionCount: 12,
    lastSeen: new Date().toISOString(),
    autoGenerated: true,
    accuracy: 0.89,
  },
]

const learningHistory: Array<{
  timestamp: string
  userAgent: string
  detectedPattern: string
  confidence: number
  wasCorrect: boolean
}> = []

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const action = searchParams.get("action") || "patterns"

    switch (action) {
      case "patterns":
        return NextResponse.json({
          success: true,
          data: learningPatterns.sort((a, b) => b.confidence - a.confidence),
        })

      case "stats":
        const stats: LearningStats = {
          totalPatterns: learningPatterns.length,
          autoGeneratedPatterns: learningPatterns.filter((p) => p.autoGenerated).length,
          averageAccuracy: learningPatterns.reduce((acc, p) => acc + p.accuracy, 0) / learningPatterns.length,
          topCategories: getTopCategories(),
          recentLearning: learningHistory.slice(-10).map((h) => ({
            timestamp: h.timestamp,
            pattern: h.detectedPattern,
            confidence: h.confidence,
          })),
        }
        return NextResponse.json({
          success: true,
          data: stats,
        })

      case "history":
        const limit = Number.parseInt(searchParams.get("limit") || "50")
        return NextResponse.json({
          success: true,
          data: learningHistory.slice(-limit),
        })

      default:
        return NextResponse.json({ success: false, error: "Invalid action" }, { status: 400 })
    }
  } catch (error) {
    console.error("Auto-learning GET error:", error)
    return NextResponse.json({ success: false, error: "Failed to fetch learning data" }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { action, data } = body

    switch (action) {
      case "learn":
        return handleLearning(data)
      case "validate":
        return handleValidation(data)
      case "discover":
        return handlePatternDiscovery(data)
      default:
        return NextResponse.json({ success: false, error: "Invalid action" }, { status: 400 })
    }
  } catch (error) {
    console.error("Auto-learning POST error:", error)
    return NextResponse.json({ success: false, error: "Failed to process learning request" }, { status: 500 })
  }
}

function handleLearning(data: any) {
  const { userAgent, isBot, actualResult } = data

  if (!userAgent || isBot === undefined) {
    return NextResponse.json({ success: false, error: "Missing required fields" }, { status: 400 })
  }

  // Find matching patterns
  const matchingPatterns = learningPatterns.filter((pattern) => new RegExp(pattern.pattern, "i").test(userAgent))

  // Update pattern accuracy based on actual result
  matchingPatterns.forEach((pattern) => {
    const wasCorrect = pattern.confidence > 0.5 === isBot
    pattern.accuracy = (pattern.accuracy * pattern.detectionCount + (wasCorrect ? 1 : 0)) / (pattern.detectionCount + 1)
    pattern.detectionCount++
    pattern.lastSeen = new Date().toISOString()
  })

  // Record learning history
  learningHistory.push({
    timestamp: new Date().toISOString(),
    userAgent,
    detectedPattern: matchingPatterns.length > 0 ? matchingPatterns[0].pattern : "none",
    confidence: matchingPatterns.length > 0 ? matchingPatterns[0].confidence : 0,
    wasCorrect: actualResult !== undefined ? actualResult === isBot : true,
  })

  // Auto-discover new patterns if existing ones failed
  if (matchingPatterns.length === 0 && isBot) {
    const newPattern = discoverNewPattern(userAgent)
    if (newPattern) {
      learningPatterns.push(newPattern)
    }
  }

  return NextResponse.json({
    success: true,
    message: "Learning data processed",
    matchingPatterns: matchingPatterns.length,
    newPatternsDiscovered: matchingPatterns.length === 0 && isBot ? 1 : 0,
  })
}

function handleValidation(data: any) {
  const { patternId, isAccurate } = data

  const pattern = learningPatterns.find((p) => p.id === patternId)
  if (!pattern) {
    return NextResponse.json({ success: false, error: "Pattern not found" }, { status: 404 })
  }

  // Update accuracy based on validation
  const currentAccuracy = pattern.accuracy * pattern.detectionCount
  const newAccuracy = (currentAccuracy + (isAccurate ? 1 : 0)) / (pattern.detectionCount + 1)

  pattern.accuracy = newAccuracy
  pattern.detectionCount++

  return NextResponse.json({
    success: true,
    message: "Pattern validation recorded",
    updatedAccuracy: newAccuracy,
  })
}

function handlePatternDiscovery(data: any) {
  const { userAgents } = data

  if (!Array.isArray(userAgents)) {
    return NextResponse.json({ success: false, error: "userAgents must be an array" }, { status: 400 })
  }

  const newPatterns: LearningPattern[] = []

  // Analyze user agents for common patterns
  const patterns = extractCommonPatterns(userAgents)

  patterns.forEach((patternData) => {
    const existingPattern = learningPatterns.find((p) => p.pattern === patternData.pattern)

    if (!existingPattern && patternData.frequency > 2) {
      const newPattern: LearningPattern = {
        id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
        pattern: patternData.pattern,
        category: categorizePattern(patternData.pattern),
        confidence: Math.min(0.8, 0.4 + patternData.frequency * 0.1),
        detectionCount: patternData.frequency,
        lastSeen: new Date().toISOString(),
        autoGenerated: true,
        accuracy: 0.5, // Start with neutral accuracy
      }

      learningPatterns.push(newPattern)
      newPatterns.push(newPattern)
    }
  })

  return NextResponse.json({
    success: true,
    message: `Discovered ${newPatterns.length} new patterns`,
    newPatterns,
  })
}

function discoverNewPattern(userAgent: string): LearningPattern | null {
  // Simple pattern discovery - look for common bot indicators
  const botIndicators = [/bot\b/i, /crawler/i, /spider/i, /scraper/i, /headless/i, /automation/i]

  for (const indicator of botIndicators) {
    if (indicator.test(userAgent)) {
      const match = userAgent.match(indicator)
      if (match) {
        return {
          id: Date.now().toString(),
          pattern: match[0].toLowerCase(),
          category: "auto_discovered",
          confidence: 0.6,
          detectionCount: 1,
          lastSeen: new Date().toISOString(),
          autoGenerated: true,
          accuracy: 0.5,
        }
      }
    }
  }

  return null
}

function extractCommonPatterns(userAgents: string[]): Array<{ pattern: string; frequency: number }> {
  const patternMap = new Map<string, number>()

  userAgents.forEach((ua) => {
    // Extract potential bot patterns
    const words = ua.toLowerCase().split(/[\s/$$$$[\];,]+/)

    words.forEach((word) => {
      if (word.length > 3 && !isCommonWord(word) && /[a-z]/.test(word)) {
        patternMap.set(word, (patternMap.get(word) || 0) + 1)
      }
    })
  })

  return Array.from(patternMap.entries())
    .map(([pattern, frequency]) => ({ pattern, frequency }))
    .filter((item) => item.frequency > 1)
    .sort((a, b) => b.frequency - a.frequency)
}

function categorizePattern(pattern: string): string {
  const categories = {
    search_engine: ["google", "bing", "yahoo", "baidu", "yandex"],
    social_media: ["facebook", "twitter", "linkedin", "instagram"],
    ad_verification: ["integral", "doubleverify", "moat", "grapeshot"],
    automation: ["headless", "selenium", "puppeteer", "phantom"],
    crawler: ["bot", "crawler", "spider", "scraper"],
  }

  for (const [category, keywords] of Object.entries(categories)) {
    if (keywords.some((keyword) => pattern.includes(keyword))) {
      return category
    }
  }

  return "unknown"
}

function isCommonWord(word: string): boolean {
  const commonWords = [
    "mozilla",
    "webkit",
    "applewebkit",
    "chrome",
    "safari",
    "firefox",
    "windows",
    "linux",
    "macintosh",
    "compatible",
    "version",
    "http",
    "https",
    "www",
    "html",
    "like",
    "gecko",
    "khtml",
  ]
  return commonWords.includes(word.toLowerCase())
}

function getTopCategories(): Array<{ category: string; count: number }> {
  const categoryMap = new Map<string, number>()

  learningPatterns.forEach((pattern) => {
    categoryMap.set(pattern.category, (categoryMap.get(pattern.category) || 0) + 1)
  })

  return Array.from(categoryMap.entries())
    .map(([category, count]) => ({ category, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 5)
}
